# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "866d5e5de98473d1f06dc99ee10018d2"
name = "Custom Bundle App"
application_url = "https://shopify-bundle-app-lrms.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_discounts"

[auth]
redirect_urls = [ "https://shopify-bundle-app-lrms.onrender.com/api/auth" ]

[app_proxy]
url = "https://shopify-bundle-app-lrms.onrender.com/api/public"
subpath = "shopify-bundle-app"
prefix = "apps"
