api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "quantity-break-discount"
type = "function"
uid = "d7ec169a-1a79-bccf-d3ff-2aac795c96746f5ee4d0"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
